---
title: "CutAndRunReport"
date: "`r Sys.Date()`"
output: html_document
params:
    samples: ["NA","NA"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
samples = params$samples
```

## Aligned read stats
```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
samples1 <- samples[grep("^((?!_merged).)*$",samples,perl=TRUE)]
for (smpl in samples1) {
  df <- (read.csv(paste0("../results/read_stats/",smpl,".csv"),header=F,row.names=1))
  names(df) <- "read counts"
  print(knitr::kable(df,caption=smpl))
}
```

## Fragment sizes plots
```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
lst <- lapply(samples,function(smpl){
  cowplot::ggdraw() + cowplot::draw_image(paste0("../results/fragment_sizes_plots/",smpl,"_fragment_sizes.png"), scale = 1)
})
cowplot::plot_grid(plotlist=lst,labels=samples,label_size = 6,ncol=2)
```

## Fragment sizes stats

```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
for (smpl in samples) {
  df <- (read.table(paste0("../results/fragment_sizes/",smpl,"_fragment_sizes_stats.txt"),sep="\t",header=T,row.names = 1))
  df <- df[grep("Min|Max|Median",names(df))]
  df <- df[grep("Frag",names(df))]
  row.names(df) <- gsub("^(.*[/])","",row.names(df),per=T)
  print(knitr::kable(df,caption=smpl))
}
```

## Fingerprint plots

```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
lst <- lapply(samples,function(smpl){
  cowplot::ggdraw() + cowplot::draw_image(paste0("../results/fingerprint_plots/",smpl,"_fingerprint.png"), scale = 1)
})
cowplot::plot_grid(plotlist=lst,labels=samples,label_size = 6,ncol=2)
```

## Fingerprint stats

```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
for (smpl in samples) {
  df <- t(read.table(paste0("../results/fingerprint_quality_metrics/",smpl,"_fingerprint_quality_metrics.txt"),sep="\t",header=T,row.names = 1))
  print(knitr::kable(df,caption=smpl))
}
```

## Scale factors
```{r results='asis', echo=FALSE, message=FALSE, warning=FALSE}
lst <- lapply(samples,function(smpl){
  df <- (read.table(paste0("../results/scale_factors/",smpl,"_scaleFactor.txt"),sep="\t",header=F,skip=1))
  names(df) <- smpl
  gsub("^(.*[/])","",row.names(df),per=T)
  row.names(df) <- gsub("([^=]+$)","",df[,1],per=T)
  row.names(df) <- gsub("=","",row.names(df))
  df[,1] <- gsub("^(.*[= ])","",df[,1],per=T)
  return(df)
})
df <- do.call("cbind",lst)
print(knitr::kable(df))
```

