trimmomatic_threads: 8
trimmomatic_adapterfile: "/usr/local/analysis/trimmomatic/0.35/lib/adapters/TruSeq3-PE-2.fa"
cutadapt_adapterfile: "/usr/local/analysis/trimmomatic/0.35/lib/adapters/TruSeq3-PE-2.fa"
bowtie2_genome: "/Volumes/cbds/hpc-nobackup/bitbucket/chipseq-cut-and-run/human_drosophilia_merged_genome/indexed_merged_genome/hg19_dm6simple_merged_genome.fasta"
bowtie2_threads: 12
bowtie2_samtools_threads: 12
sicer_genome: "hg19"
sicer_windowSize: 200
sicer_fragmentSize: 150
sicer_fdr: 0.01
sicer_gapSize: 600
blacklist_file: "resources/hg19-blacklist.v2.bed"
