# samples file
samples_csv: "config/samples.csv"
# trimmomatic options:
trimmomatic_threads: 8
trimmomatic_adapterfile: "/usr/local/analysis/trimmomatic/0.35/lib/adapters/TruSeq3-PE-2.fa"
# cutadapt options
cutadapt_adapterfile: "/usr/local/analysis/trimmomatic/0.35/lib/adapters/TruSeq3-PE-2.fa"
# bowtie2 options
bowtie2_genome: "/Volumes/Sansam/hpc-nobackup/bowtie2Indexes/hg38_ecoli_sacCer3_bowtie2Index/hg38_ecoli_sacCer3"
bowtie2_threads: 12
bowtie2_samtools_threads: 12
# sicer options:
sicer_genome: "hg38"
sicer_windowSize: 200
sicer_fragmentSize: 150
sicer_fdr: 0.01
sicer_gapSize: 600
blacklist_file: "resources/hg38-blacklist.v2.bed"
# macs2 options
## for effective genome sizes see: https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html
macs2_effective_genome_size: 2913022398
# macs2 "normal" options
macs2_minimum_FDR_cutoff: 0.05
# macs2 "broad" options
macs2_broad_minimum_FDR_cutoff: 0.1
